jwt:
  jwt_secret:
    type: password
    value: boxvault-secret-key
    description: Secret key for JWT
  jwt_token_time_valid:
    type: integer
    value: 86400
    description: JWT token validity time in seconds (24 hours)
