schemaVersion: 1
auth:
  enabled_strategies:
    - local
    - jwt
    - oidc
  default_strategy: local
  jwt:
    jwt_secret: ${JWT_SECRET}
    jwt_expiration: 24h
    jwt_issuer: boxvault
    jwt_audience: boxvault
    download_link_expiry: 1h
    invitation_token_expiry_hours: 24
    verification_token_expiry_hours: 24
    service_account_max_expiry_days: 365
    local_enabled: true
  local:
    local_require_email_verification: true
    local_password_min_length: 15
    local_password_require_uppercase: false
    local_password_require_lowercase: false
    local_password_require_numbers: false
    local_password_require_symbols: false
    local_bcrypt_rounds: 10
    local_session_timeout: 24
    local_allow_new_organizations: false
  oidc:
    token_refresh_threshold_minutes: 5
    token_default_expiry_minutes: 30
    default_provider: ''
    silent_login: false
    providers: {}
  resource_server:
    enabled: false
    audience: boxvault
  external:
    domain_mapping_enabled: true
    domain_mappings: |
      {
        "A55D94": ["m4kr.net", "philotic.cloud"]
      }
    provisioning_enabled: true
    provisioning_policy: invite_only
    provisioning_default_role: user
    provisioning_fallback_action: create_org
    profile_sync_enabled: true
    profile_update_on_login: true
    profile_sync_fields: displayName,email,groups
