schemaVersion: 1
database_type: sqlite
sql:
  host: localhost
  port: 3306
  logging: false
  user: boxvault
  password: CHANGE_THIS_PASSWORD
  database: boxvault
  storage: /var/lib/boxvault/database/boxvault.db
  dialect: ''
mysql_pool:
  max: 5
  min: 0
  acquire: 30000
  idle: 5000
