schemaVersion: 1
smtp_connect:
  host: smtp.example.com
  port: 587
  secure: true
  rejectUnauthorized: true
smtp_settings:
  from: noreply@your-domain.com
  replyTo: support@your-domain.com
  rateLimit: 10
  alert_emails: []
smtp_auth:
  user: your-smtp-username
  password: CHANGE_THIS_SMTP_PASSWORD
