smtp_connect:
  host:
    type: host
    value: smtp.example.com
    description: SMTP server hostname
  port:
    type: integer
    value: '587'
    description: SMTP server port
  secure:
    type: boolean
    value: true
    description: Use TLS for connection
  rejectUnauthorized:
    type: boolean
    value: true
    description: Reject unauthorized TLS connections
smtp_settings:
  from:
    type: email
    value: noreply@your-domain.com
    description: Default sender email address
  replyTo:
    type: email
    value: support@your-domain.com
    description: Default reply-to email address
  rateLimit:
    type: integer
    value: '10'
    description: Maximum emails to send per second
smtp_auth:
  user:
    type: string
    value: your-smtp-username
    description: SMTP username
  password:
    type: password
    value: CHANGE_THIS_SMTP_PASSWORD
    description: SMTP password
